version: '3.9'

services:
  expenses-1:
    image: renatojsilvas/expenses-staging:latest
    hostname: expenses-1
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - expenses-network-staging

  expenses-2:
    image: renatojsilvas/expenses-staging:latest
    hostname: expenses-2
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - expenses-network-staging

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9001:8080"
    depends_on:
      - expenses-1
      - expenses-2
    networks:
      - expenses-network-staging

networks:
  expenses-network-staging:
    driver: bridge